### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by LIUHaohui** [i40-Tools/Alligator-Frontend#1]
When I use the "webpack" command, it appears that:

Hash: e5385694909a077282f3
Version: webpack 1.15.0
Time: 5468ms
        Asset     Size  Chunks             Chunk Names
client.min.js  3.25 MB       0  [emitted]  main
    + 245 hidden modules

ERROR in ./js/pages/Home.js
Module not found: Error: Cannot resolve module 'vkbeautify' in /Users/liuhaohui/Desktop/4th/Alligator-Frontend-master/src/js/pages
 @ ./js/pages/Home.js 30:18-39

I was wondering if there is anything wrong with my setting?

**Comment by omarrana** [comment]
you need to install vkbeautify .  try google npm install vkbeautify

________________________________

**Comment by LIUHaohui** [comment]
Problem solved, Thank you so much for the fast and accurate reply.
